# ------------------------------------------------------------ Pipeline------------------------------------------------------------
kind: pipeline
type: docker
name: Orion.IBE

clone:
  disable: true

steps:
  - name: Clone
    image: alpine/git
    commands:
    - git -c http.sslVerify=false clone -b $DRONE_COMMIT_BRANCH https://$${creds}@git.dision.office/Orion/orion.frontend.git
      
  - name: Prebuildd & Build Staging
    image: node:18-alpine
    commands:
    - yarn --cwd orion.frontend install
    - yarn --cwd orion.frontend build:dev
    when:
      branch:
      - staging
      - feat/drone

  - name: Prebuildd & Build Prod
    image: node:18-alpine
    commands:
    - yarn --cwd orion.frontend install
    - yarn --cwd orion.frontend build:prod
    when:
      branch:
      - main

  - name: Unit Test
    image: mcr.microsoft.com/playwright:v1.37.0-jammy
    commands:
    - yarn --cwd orion.frontend test

  - name: Transfer to staging
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: orion-host-2
      username:
        from_secret: orion-host-2-user
      password:
        from_secret: orion-host-2-password
      target: /tmp/ibe
      source: /drone/src/orion.frontend/out-development
      strip_components: 3
    when:
      branch:
      - staging
      - feat/drone

  - name: Deploy to staging
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: orion-host-2
      username:
        from_secret: orion-host-2-user
      password:
        from_secret: orion-host-2-password
      script:
        - /tmp/ibe.sync
    when:
      branch:
      - staging

  - name: Transfer to Netcup
    image: drillster/drone-rsync
    settings:
      hosts:
        from_secret: netcup-host
      user:
        from_secret: netcup-host-user
      key:
        from_secret: netcup-key
      source: /drone/src/orion.frontend/out
      target: /data/shared/orion/frontend/ibe
      recursive: true
      delete: true
    when:
      branch:
      - main

node:
  proxmox: docker-runner01

---
kind: pipeline
type: docker
name: Noti

clone:
  disable: true

steps:
  - name: Notification
    image: parrazam/drone-ntfy
    when:
        status: [success, failure]
    settings:
      url: http://drone-ntfy
      topic: drone-events
      priority: high
      tags: 
        - pipeline-status
        - dev
      username:
        from_secret: ntfy_user
      password:
        from_secret: ntfy_password

depends_on:
  - Orion.IBE